- name: Try azure_rest module
  hosts: localhost
  connection: local
  tasks:
  - name: Create a batch account
    azure_rm_rest:
      url: /subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/zimsnewansible/providers/Microsoft.Batch/batchAccounts/zimsbatchaccount
      api_version: "2017-09-01"
      method: PUT
      body:
        location: eastus
        #properties:
        #  poolAllocationMode: UserSubscription
      status_code:
        - 200
        - 202
  - name: Query batch account
    azure_rm_rest:
      url: /subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/zimsnewansible/providers/Microsoft.Batch/batchAccounts/zimsbatchaccount
      api_version: "2017-09-01"
      status_code:
        - 200
        - 201
    register: output
  - name: Dump output 
    debug:
      msg: "{{ output }}"
